name = "Dithering"
uuid = "0974bddb-ffe7-4d59-96d4-d2a78da66510"
authors = ["Darryl Gamroth <dgamroth@rubus.ca>"]
version = "0.3.0"

[deps]

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[targets]
test = ["Test", "Statistics", "FFTW", "LinearAlgebra"]
